#!/bin/bash

exIN="$@"

if [ -z "$@" ]; then
	exIN="10"
fi

hex1="303031313132323333343435353636373738383939"
unpacked="$(echo $hex1 | xxd -r -ps)"
length="$(($(echo "$unpacked" | wc -c)-1))"

for I in $(seq $exIN); do
	selector="$(($RANDOM%$length))"
	echo ${unpacked:$selector:1}
done
